version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - desenvolvimento-network

  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - desenvolvimento-network

networks:
  desenvolvimento-network:
    name: desenvolvimento-network
    driver: bridge

volumes:
  postgres_data:
